# Generated by Django 5.2.13 on 2026-04-26 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HojaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.UUIDField(unique=True)),
                ('nro_entrega', models.CharField(max_length=64)),
                ('fecha', models.DateField()),
                ('transporte_tipo', models.CharField(blank=True, max_length=100)),
                ('flete', models.CharField(blank=True, max_length=100)),
                ('chofer', models.CharField(blank=True, max_length=120)),
                ('acompanante', models.CharField(blank=True, max_length=120)),
                ('transporte', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(choices=[('importada', 'Importada'), ('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='importada', max_length=20)),
                ('archivo_pdf_original', models.FileField(blank=True, upload_to='hojas-ruta/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Remito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remito_uid', models.CharField(max_length=120)),
                ('numero', models.CharField(max_length=50)),
                ('cliente', models.CharField(max_length=180)),
                ('subcliente', models.CharField(blank=True, max_length=180)),
                ('direccion', models.CharField(max_length=250)),
                ('observacion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('evidencia_cargada', 'Evidencia cargada'), ('intento_fallido', 'Intento fallido'), ('validado', 'Validado'), ('observado', 'Observado'), ('rechazado', 'Rechazado'), ('cerrado', 'Cerrado')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hoja_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remitos', to='tracking.hojaruta')),
            ],
            options={
                'unique_together': {('hoja_ruta', 'remito_uid')},
            },
        ),
        migrations.CreateModel(
            name='IntentoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('logistica', 'Logistica'), ('cliente', 'Cliente'), ('interno', 'Interno')], max_length=20)),
                ('motivo', models.CharField(max_length=120)),
                ('comentario', models.TextField(blank=True)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('hoja_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='tracking.hojaruta')),
                ('remito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='tracking.remito')),
            ],
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('logistica', 'Logistica'), ('cliente', 'Cliente'), ('interno', 'Interno')], max_length=20)),
                ('archivo', models.FileField(upload_to='conformados/%Y/%m/%d')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('estado_validacion', models.CharField(choices=[('pendiente_revision', 'Pendiente revision'), ('validada', 'Validada'), ('observada', 'Observada'), ('rechazada', 'Rechazada')], default='pendiente_revision', max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('origen', models.CharField(blank=True, max_length=120)),
                ('hoja_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='tracking.hojaruta')),
                ('remito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='tracking.remito')),
            ],
        ),
        migrations.CreateModel(
            name='EventoTrazabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('importacion', 'Importacion'), ('apertura_link', 'Apertura link'), ('carga_evidencia', 'Carga evidencia'), ('intento_fallido', 'Intento fallido'), ('validacion', 'Validacion'), ('rechazo', 'Rechazo'), ('cierre', 'Cierre')], max_length=30)),
                ('canal', models.CharField(blank=True, max_length=20)),
                ('detalle', models.TextField(blank=True)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('hoja_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='tracking.hojaruta')),
                ('remito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='tracking.remito')),
            ],
            options={
                'ordering': ['-fecha_evento'],
            },
        ),
    ]
