# Generated by Django 5.2.13 on 2026-04-26 15:55

import tracking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='archivo',
            field=models.FileField(upload_to=tracking.models.conformado_upload_to),
        ),
        migrations.AlterField(
            model_name='hojaruta',
            name='archivo_pdf_original',
            field=models.FileField(blank=True, upload_to=tracking.models.hoja_ruta_pdf_upload_to),
        ),
    ]
