# Generated by Django 6.0 on 2026-05-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='remito',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
