# Generated by Django 6.0 on 2026-05-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_remito_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoAccesoPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(max_length=20)),
                ('oid', models.CharField(max_length=64)),
                ('motivo', models.CharField(choices=[('oid_invalido', 'OID invalido'), ('hoja_inexistente', 'Hoja inexistente')], max_length=30)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.TextField(blank=True)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('detalle', models.TextField(blank=True)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_evento'],
            },
        ),
    ]
