# Generated by Django 6.0 on 2026-05-10 21:54

from django.db import migrations, models


def seed_audit_remitos_permission(apps, schema_editor):
    RoleDefinition = apps.get_model("tracking", "RoleDefinition")
    RoleDefinition.objects.filter(can_review_evidence=True).update(can_audit_remitos=True)


def unseed_audit_remitos_permission(apps, schema_editor):
    RoleDefinition = apps.get_model("tracking", "RoleDefinition")
    RoleDefinition.objects.update(can_audit_remitos=False)


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_multi_empresa_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='roledefinition',
            name='can_audit_remitos',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(seed_audit_remitos_permission, unseed_audit_remitos_permission),
    ]
