# Generated by Django 5.2.13 on 2026-05-15 11:49

import tracking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_role_audit_remitos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='archivo',
            field=models.FileField(max_length=200, upload_to=tracking.models.conformado_upload_to),
        ),
        migrations.AlterField(
            model_name='hojaruta',
            name='archivo_pdf_original',
            field=models.FileField(blank=True, max_length=200, upload_to=tracking.models.hoja_ruta_pdf_upload_to),
        ),
    ]
