# Generated by Django 5.2.13 on 2026-05-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_increase_archivo_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojaruta',
            name='motivo_anulacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='roledefinition',
            name='can_anular_hoja',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventotrazabilidad',
            name='tipo',
            field=models.CharField(choices=[('importacion', 'Importacion'), ('apertura_link', 'Apertura link'), ('carga_evidencia', 'Carga evidencia'), ('intento_fallido', 'Intento fallido'), ('validacion', 'Validacion'), ('rechazo', 'Rechazo'), ('cierre', 'Cierre'), ('anulacion', 'Anulacion')], max_length=30),
        ),
        migrations.AlterField(
            model_name='hojaruta',
            name='estado',
            field=models.CharField(choices=[('importada', 'Importada'), ('abierta', 'Abierta'), ('cerrada', 'Cerrada'), ('anulada', 'Anulada')], default='importada', max_length=20),
        ),
    ]
