# Generated by Django 5.2.13 on 2026-05-30 23:45

import tracking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_anular_hoja_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentoentrega',
            name='archivo',
            field=models.FileField(blank=True, max_length=200, upload_to=tracking.models.intento_upload_to),
        ),
    ]
